---
# =============================================================================
# Ansible Role: Users - Handlers
# =============================================================================
# This file defines handlers that can be triggered by tasks to perform
# service management operations. Handlers run only once at the end of plays,
# even if notified multiple times.
#
# Each handler restarts a specific service after configuration changes.
# =============================================================================
