# =============================================================================
# Ansible Role: Users - Molecule Preparation Playbook
# =============================================================================
# This playbook prepares the test environment for Molecule testing.
# It performs necessary system preparations before role execution:
# - Fixes file permissions
# - Validates system requirements
# - Sets up required dependencies
#
# Flow:
# 1. Fix system file permissions
# 2. Validate system state
# =============================================================================

---
# -----------------------------------------------------------------------------
# 1. System Preparation
# -----------------------------------------------------------------------------
- name: molecule | Prepare
  hosts: all
  gather_facts: false

  tasks:
    - name: Prepare | Wait for system initialization
      ansible.builtin.wait_for_connection:
        delay: 2
        timeout: 60

    - name: Prepare | Gather facts
      ansible.builtin.setup:

    - name: Prepare | Fix /etc/shadow permissions
      register: etc_shadow
      ansible.builtin.shell:
        cmd: |
          echo ""
          ls -l /etc/shadow
          chmod 0400 /etc/shadow
          ls -l /etc/shadow
          echo ""
      changed_when: false

    - name: Prepare | Ensure required packages are installed
      delegate_to: localhost
      ansible.builtin.package:
        name:
          - python3-pip  # Adding pip for Python modules
        state: present
      when: ansible_pkg_mgr in ['apt', 'dnf', 'yum']

    - name: Prepare | Install passlib Python module (required for password hashing)
      delegate_to: localhost
      ansible.builtin.pip:
        name: passlib
        state: present

    - name: Prepare | Create test groups
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      with_items:
        - testgroup
        - developers
